#Roll two dice.  Let X be the value on the first die and let Y be the value on the second die.  Then both X and Y take values 1 to 6 and the joint pmf isp(i, j) = 1/36 for all i and j between 1 and 6.  Here is the joint probability table:

In [4]:
import numpy as np
#joint probablity
print("X\Y   1         2         3         4         5         6")
for i in range(1,6+1):
    print(i)
    for j in range(1,6+1):
        print("   (",round(1/36,2),")",end="")
    print("\n")

X\Y   1         2         3         4         5         6
1
   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )

2
   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )

3
   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )

4
   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )

5
   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )

6
   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )   ( 0.03 )



In [3]:
# Marginal probablity
arr = np.array([[0.03,0.03,0.03,0.03,0.03,0.03],[0.03,0.03,0.03,0.03,0.03,0.03],[0.03,0.03,0.03,0.03,0.03,0.03],[0.03,0.03,0.03,0.03,0.03,0.03],[0.03,0.03,0.03,0.03,0.03,0.03],[0.03,0.03,0.03,0.03,0.03,0.03]])
print("Joint probablity is of two dices")
print(arr)
x1 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
x2 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
x3 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
x4 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
x5 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
x6 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
y1 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
y2 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
y3 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
y4 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
y5 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
y6 = np.array([0.03,0.03,0.03,0.03,0.03,0.03])
print("marginal Probablity is:")
print("x == 1:",sum(x1))
print("x == 2:",sum(x2))
print("x == 3:",sum(x3))
print("x == 4:",sum(x4))
print("x == 5:",sum(x5))
print("x == 6:",sum(x6))
print("y== 1 :",sum(y1))
print("y== 2 :",sum(y2))
print("y== 3 :",sum(y3))
print("y== 4 :",sum(y4))
print("y== 5 :",sum(y5))
print("y== 6 :",sum(y6))

Joint probablity is of two dices
[[0.03 0.03 0.03 0.03 0.03 0.03]
 [0.03 0.03 0.03 0.03 0.03 0.03]
 [0.03 0.03 0.03 0.03 0.03 0.03]
 [0.03 0.03 0.03 0.03 0.03 0.03]
 [0.03 0.03 0.03 0.03 0.03 0.03]
 [0.03 0.03 0.03 0.03 0.03 0.03]]
marginal Probablity is:
x == 1: 0.18
x == 2: 0.18
x == 3: 0.18
x == 4: 0.18
x == 5: 0.18
x == 6: 0.18
y== 1 : 0.18
y== 2 : 0.18
y== 3 : 0.18
y== 4 : 0.18
y== 5 : 0.18
y== 6 : 0.18
